import {
  Controller,
  Post,
  Get,
  Delete,
  Body,
  Param,
  Query,
  UseGuards,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import { ApiTags, ApiBearerAuth, ApiOperation, ApiResponse } from '@nestjs/swagger';
import { BillService } from './bill.service';
import { CreateBillDto } from './dto/create-bill.dto';
import { PaginationDto } from '../../common/dto/pagination.dto';
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';
import { CurrentMerchant } from '../../common/decorators/current-merchant.decorator';

@ApiTags('Bills')
@ApiBearerAuth()
@UseGuards(JwtAuthGuard)
@Controller('bills')
export class BillController {
  constructor(private readonly billService: BillService) {}

  @Post()
  @ApiOperation({ summary: 'Checkout and generate new invoice (bill)' })
  @ApiResponse({ status: 201, description: 'Invoice successfully generated and stock deducted if enabled' })
  @ApiResponse({ status: 400, description: 'Insufficient stock or invalid request data' })
  @ApiResponse({ status: 404, description: 'Product not found' })
  async create(
    @Body() dto: CreateBillDto,
    @CurrentMerchant('id') merchantId: string,
  ) {
    const bill = await this.billService.create(dto, merchantId);
    return {
      success: true,
      message: 'Invoice generated successfully.',
      data: bill,
    };
  }

  @Get()
  @ApiOperation({ summary: 'Get paginated billing invoices generated by merchant' })
  @ApiResponse({ status: 200, description: 'Paginated invoices lists' })
  async findAll(
    @Query() paginationDto: PaginationDto,
    @CurrentMerchant('id') merchantId: string,
  ) {
    const result = await this.billService.findAll(merchantId, paginationDto);
    return {
      success: true,
      ...result,
    };
  }

  @Get(':id')
  @ApiOperation({ summary: 'Get invoice detailed line items by ID' })
  @ApiResponse({ status: 200, description: 'Invoice structure returned' })
  @ApiResponse({ status: 404, description: 'Invoice not found' })
  async findOne(
    @Param('id') id: string,
    @CurrentMerchant('id') merchantId: string,
  ) {
    const bill = await this.billService.findOne(id, merchantId);
    return {
      success: true,
      data: bill,
    };
  }

  @Delete(':id')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Soft-delete an invoice' })
  @ApiResponse({ status: 200, description: 'Invoice soft-deleted successfully' })
  @ApiResponse({ status: 404, description: 'Invoice not found' })
  async remove(
    @Param('id') id: string,
    @CurrentMerchant('id') merchantId: string,
  ) {
    await this.billService.delete(id, merchantId);
    return {
      success: true,
      message: 'Invoice soft-deleted successfully.',
    };
  }
}
